### PR TITLE
add support for hierarchical MODULEPATHs

### PR DESCRIPTION
**Pull request by JLague**
This PR adds support for hierarchical MODULEPATHs using Lmod's `spider` command. Similar to the lua feature, it does not come by default and can be enabled by specifying `MII_ENABLE_SPIDER=yes` at build time.

## Additions/Modifications
- Add a `parents` array to the modtable entry. Because this is saved and retrieved from the index, it is not compatible with indices from previous versions of `mii`.
- Use the `spider` command and parse the resulting JSON to fill up the index. This is what is enabled by setting `MII_ENABLE_SPIDER` to `yes`.
- Sort every type of search based on more factors. For example, for every parent that is already loaded, the module will appear higher in the search result and newer versions of the same module will appear first. See `_mii_search_result_compare` and `_mii_search_result_get_priority` for the implementation.
- Load the parents and the module before executing the command that was searched.

## Limitations
Because Lmod's `spider` command retrieves every info necessary to build the index in one sweep, it cannot be used to sync the index (or atleast I don't know of a good way to do it). We have decided to only use the `spider` command when building the index and to keep the sync the way it was. Since only the analysed modules are exported to the index and the sync does not analyse the new MODULEPATHs, using the sync will remove the modules in the new MODULEPATHs from the index. This is fine for us, because we plan on using a global index which won't be rebuilt on every login.

I am open to suggestions on a better way to do it.

## Added "dependencies"

This new feature uses the [cJSON](https://github.com/DaveGamble/cJSON) library and needs Lmod to function (Lmod needs to be installed and `LMOD_DIR` needs to be set).

### CODE REVIEW

**Comment by mboisson** [comment]
This is for https://github.com/codeandkey/mii/issues/4

**Comment by codeandkey** [comment]
I am glad this feature is working on your systems! Sorry for the late response to this PR -- there are a ton of changes here and there may be more to do before this is merged. Using the `spider` command is a great approach to locate the dependent modules. I am worried this may break too many other features however - particularly the Tcl module support and the synchronizing process.

The `parent` field is great and should be sufficient to store the module loading hierarchy, but the removal of MODULEPATHs prevents detecting new modules on sync. The only way I see to keep synchronizing working is to include an additional field in modules (similar to `bins`) which stores any child MODULEPATHs.

I think that to maintain support for both Lmod and Tcl modules it may be best to modify the analysis to scan for these additional MODULEPATHs and recursively include dependent modules into the index. This would eliminate the dependency on the `spider` command and likely the `cJSON` library as well.

I will not be able to dedicate as much time towards this feature for now with classes beginning again but this is really great progress. Thank you @JLague!

**Comment by mboisson** [comment]
I don't know whether hierarchical module paths are really used in Tcl ? They can't be very useful without the `module spider` feature, since users can't easily discover what they provide. 

That was the rationale with which this was developed. Basically, the assumption was that module hierarchies are really only used with Lmod, not TCL mode. 

We did discuss internally the lack of support for sync using this method. We decided to reduce the scope of work for @JLague because generating the index was so quick, and we did not actually want local indexes generated by users, as this would create more load on the filesystems, and possibly create inconsistencies. Since we primarily work in a scheme in which software installation is performed centrally by HPC analysts, generating the index at the time of installing a new piece of software made more sense to us.

**Comment by codeandkey** [comment]
I see, I agree that I haven't actually come across any hierarchical Tcl modules in practice. If standard practice is to only have embedded `MODULEPATH` in Lmod modules then that is great to hear. In that case the `module spider` approach is awesome.

Centralizing the index makes a lot of sense too. There's no need for the sync feature if building from scratch takes a reasonable amount of time and is globally available. However this does require Mii to be installed system-wide so I feel it might not be best for this to be default behavior. 

As the sync does not behave properly when this feature is enabled, I think it will be OK to just disable the sync feature and have Mii terminate when syncing with `MII_ENABLE_SPIDER` set. In the future it would be nice to include embedded module paths in index entries so the sync can behave correctly; I will open a separate issue for this.

Thank you @mboisson for the update and your input.

**Comment by codeandkey** [comment]
Everything is working great, I will go ahead and merge this. Thank you again @JLague for your hard work!

**Pull request merged**
