### PR TITLE
Add runtime interactive shell detection

### LINKED ISSUE #12: interactive shell detection must be done in the handler, not in the initi
**Describe the bug**
In a typical Slurm cluster, the login node environment will be exported to the job. That means the detection of whether a shell is interactive or not can't be done at "init" time (i.e. in the `bash` or `zsh` script). It must rather be done in the handler (currently in `common`).

### PR DESCRIPTION
**Pull request by codeandkey**
This adds an interactive shell test at command time as well as init time. When a non-existing command is executed in a non-interactive shell a normal error message is displayed.

Fixes #12

### CODE REVIEW

**Comment by mboisson** [comment]
ah, I was about to submit a patch, which did the detection inside of `common`, rather than defining a variable externally, which is then used in `common`: 

https://github.com/ComputeCanada/easybuild-easyconfigs/commit/c41bd71003542bc4e2e74a88ce4219e0ff8ed613#diff-fe51bacbb3d944c17c667f4d1baffdad32ea61c7eb1565bd573f391d96c5fd14

Any reason you do the detection outside instead of in `common` ?

**Comment by mboisson** [comment]
note that `[[ $- == *i* ]]` should work in ZSH as well as in Bash

**Comment by codeandkey** [comment]
> note that `[[ $- == *i* ]]` should work in ZSH as well as in Bash

I did not know that! I figured the detection would have to be specific to each shell; in this case adding a portable test to `common` will definitely be better. If you submit this patch as a PR I am happy to review it :)

**Comment by mboisson** [comment]
done in https://github.com/codeandkey/mii/pull/14

**Pull request closed without merging**
